---
- hosts: all
  vars_prompt:
    - name: usuario
      prompt: Usuario del curso a borrar 
      private: no
  
  tasks:
    - name: Remove a profile
      win_user_profile:
        username: "{{ usuario }}"
        state: absent

    - name: delete users
      win_user:
        name: "{{ usuario }}"
        state: absent