---
- hosts: all
  vars_prompt:
    - name: usuario
      prompt: Usuario del curso 
      private: no
 
  tasks:
    
    - name: Create the user
      win_user:
        name: "{{ username }}"
        password: "{{username}}"
        groups: Users
        state: present
    
    - name: Remove user from the Power Users group
      win_user:
        name: "{{ username }}"
        groups: Power Users
        state: absent
