---
- name: Create user without permissions to install programs
  hosts: all
  become: yes
  tasks:
  
    - name: Create new user (Windows)
      user:
        name: "{{ user_name }}"
        password: "{{ user_name }}"
        update_password: always
        state: present
        groups: "{{ user_groups }}"
        append: yes
      when: ansible_os_family == 'Windows'
  
    - name: Remove permissions to install programs (Windows)
      win_group_membership:
        name: "{{ user_name }}"
        group_name: Administrators
        state: absent
      when: ansible_os_family == 'Windows'
  
    - name: Create new user (Linux)
      user:
        name: "{{ user_name }}"
        password: "{{ user_name }}"
        state: present
        groups: "{{ user_groups }}"
        shell: /bin/bash
      when: ansible_os_family == 'Linux'
  
    - name: Remove permissions to install programs (Linux)
      lineinfile:
        path: /etc/sudoers
        line: "{{ user_name }} ALL=(ALL) NOPASSWD: /usr/bin/apt-get, /usr/bin/yum, /usr/bin/dnf"
        state: present
      when: ansible_os_family == 'Linux'

- name: Install software
  hosts: all
  become: yes
  tasks:
    - name: Install 7zip
      win_chocolatey:
        name: 7zip
        state: present
      when: ansible_os_family == 'Windows'

    - name: Install chrome
      win_chocolatey:
        name: googlechrome
        state: present
      when: ansible_os_family == 'Windows'
    
    - name: Install notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present
      when: ansible_os_family == 'Windows'
    
    - name: Install unzip
      package:
        name: unzip
        state: present
      when: ansible_os_family == 'Linux'
    
    - name: Install chromium
      package:
        name: chromium
        state: present
      when: ansible_os_family == 'Linux'
    
    - name: Install geany
      package:
        name: geany
        state: present
      when: ansible_os_family == 'Linux'