---
- name: Update Windows
  hosts: all
  gather_facts: false
  tasks:

  - name: Check for updates
    win_updates:
      category_names: ['CriticalUpdates', 'Updates']
      state: installed

  - name: Reboot if required
    win_reboot:
  when: ansible_win_updates.reboot_required